import numpy as np
# array = np.ones([3,3],int)
# b = np.identity(3)
# print(array)
# c = np.arange(9).reshape(3,3)
# sum = np.sum(c, axis=1)
# sum1 = np.sum(c)
# print(sum)
# print(sum1)
# # print(b)
# # print(c)
# mul = np.dot(c,c)
# print(mul)

array1 = np.arange(12)
array2 = array1.reshape(6,2)
array3 = array2.reshape(3,4)
print(array1)
print(array2)
print(array3)
print(np.mean(array1, axis=0))
print(np.mean(array2, axis=1))
print(np.mean(array3, axis=1))
